name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy-to-fly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: actions/setup-go@v4
        with:
          go-version: "^1.20"

      - name: Build Swagger
        run: go install github.com/swaggo/swag/cmd/swag@latest && swag init

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
